services:
  _defaults:
    autowire: true
    autoconfigure: true

  Gadget\Cache\:
    resource: "../../../src/"
    exclude:
      - "../../../src/DependencyInjection/"
      - "../../../src/Entity/"
      - "../../../src/Kernel.php"
